# Generated by Django 5.0.6 on 2024-06-23 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('stock', models.SmallIntegerField(default=50)),
                ('primary_img', models.ImageField(upload_to='media/cpu')),
                ('second_img', models.ImageField(upload_to='media/cpu')),
            ],
        ),
    ]
