# Generated by Django 5.0.6 on 2024-06-23 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('stock', models.SmallIntegerField(default=50)),
                ('primary_img', models.ImageField(upload_to='media/gpu')),
                ('second_img', models.ImageField(upload_to='media/gpu')),
            ],
        ),
    ]
