# Generated by Django 5.0.6 on 2024-06-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='non-category', max_length=100),
        ),
    ]
