# Generated by Django 5.0.6 on 2024-06-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_gpu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpu',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Generic', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_img',
            field=models.ImageField(default=None, upload_to='media/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='second_img',
            field=models.ImageField(default=None, upload_to='media/products'),
        ),
        migrations.DeleteModel(
            name='CPU',
        ),
        migrations.DeleteModel(
            name='GPU',
        ),
    ]
