# Generated by Django 5.0.6 on 2024-06-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_gpu_product_product_brand_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_img',
            field=models.ImageField(default=None, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_img',
            field=models.ImageField(default=None, upload_to='products/'),
        ),
    ]
