# Generated by Django 5.0.6 on 2024-06-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_second_img_alter_product_primary_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='second_img',
            field=models.ImageField(default=None, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_img',
            field=models.ImageField(default=None, upload_to='products/'),
        ),
    ]
