# Generated by Django 5.0.6 on 2024-06-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
