# Generated by Django 5.0.6 on 2024-06-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_second_img_alter_product_primary_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_img',
            field=models.ImageField(default=None, upload_to='media/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_img',
            field=models.ImageField(default=None, upload_to='media/products/'),
        ),
    ]
