# Generated by Django 5.0.6 on 2024-06-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.CharField(default='General', max_length=200),
        ),
    ]
