# Generated by Django 5.0.6 on 2024-06-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_products_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_img',
            field=models.ImageField(upload_to='store/static/media/products'),
        ),
    ]
