# Generated by Django 5.0.6 on 2024-06-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_products_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.CharField(max_length=200),
        ),
    ]
