# Generated by Django 5.0.6 on 2024-06-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_products_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.PositiveIntegerField(),
        ),
    ]
