# Generated by Django 5.0.6 on 2024-06-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_products_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_stock',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
