# Generated by Django 5.0.6 on 2024-06-17 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_products_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_name', models.CharField(max_length=100)),
                ('accessory_brand', models.CharField(max_length=200)),
                ('accessory_description', models.TextField(null=True)),
                ('accessory_img', models.ImageField(upload_to='store/static/media/products')),
                ('accessory_price', models.PositiveIntegerField()),
                ('accessory_stock', models.IntegerField(default=0)),
                ('accessory_date_created', models.DateTimeField(auto_now_add=True)),
                ('accessory_date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=100)),
                ('case_brand', models.CharField(max_length=200)),
                ('case_description', models.TextField(null=True)),
                ('case_img', models.ImageField(upload_to='store/static/media/products')),
                ('case_price', models.PositiveIntegerField()),
                ('case_stock', models.IntegerField(default=0)),
                ('case_date_created', models.DateTimeField(auto_now_add=True)),
                ('case_date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_name', models.CharField(max_length=100)),
                ('chair_brand', models.CharField(max_length=200)),
                ('chair_description', models.TextField(null=True)),
                ('chair_img', models.ImageField(upload_to='store/static/media/products')),
                ('chair_price', models.PositiveIntegerField()),
                ('chair_stock', models.IntegerField(default=0)),
                ('chair_date_created', models.DateTimeField(auto_now_add=True)),
                ('chair_date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Graphics_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('card_brand', models.CharField(max_length=200)),
                ('card_description', models.TextField(null=True)),
                ('card_img', models.ImageField(upload_to='store/static/media/products')),
                ('card_price', models.PositiveIntegerField()),
                ('card_stock', models.IntegerField(default=0)),
                ('card_date_created', models.DateTimeField(auto_now_add=True)),
                ('card_date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeadPhones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headPhones_name', models.CharField(max_length=100)),
                ('headPhones_brand', models.CharField(max_length=200)),
                ('headPhones_description', models.TextField(null=True)),
                ('headPhones_img', models.ImageField(upload_to='store/static/media/products')),
                ('headPhones_price', models.PositiveIntegerField()),
                ('headPhones_stock', models.IntegerField(default=0)),
                ('headPhones_date_created', models.DateTimeField(auto_now_add=True)),
                ('headPhones_date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyboard_name', models.CharField(max_length=100)),
                ('keyboard_brand', models.CharField(max_length=200)),
                ('keyboard_description', models.TextField(null=True)),
                ('keyboard_img', models.ImageField(upload_to='store/static/media/products')),
                ('keyboard_price', models.PositiveIntegerField()),
                ('keyboard_stock', models.IntegerField(default=0)),
                ('keyboard_date_created', models.DateTimeField(auto_now_add=True)),
                ('keyboard_date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_name', models.CharField(max_length=100)),
                ('monitor_brand', models.CharField(max_length=200)),
                ('monitor_description', models.TextField(null=True)),
                ('monitor_img', models.ImageField(upload_to='store/static/media/products')),
                ('monitor_price', models.PositiveIntegerField()),
                ('monitor_stock', models.IntegerField(default=0)),
                ('monitor_date_created', models.DateTimeField(auto_now_add=True)),
                ('monitor_date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherBoard_name', models.CharField(max_length=100)),
                ('motherBoard_brand', models.CharField(max_length=200)),
                ('motherBoard_description', models.TextField(null=True)),
                ('motherBoard_img', models.ImageField(upload_to='store/static/media/products')),
                ('motherBoard_price', models.PositiveIntegerField()),
                ('motherBoard_stock', models.IntegerField(default=0)),
                ('motherBoard_date_created', models.DateTimeField(auto_now_add=True)),
                ('motherBoard_date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Power_supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_name', models.CharField(max_length=100)),
                ('power_brand', models.CharField(max_length=200)),
                ('power_description', models.TextField(null=True)),
                ('power_img', models.ImageField(upload_to='store/static/media/products')),
                ('power_price', models.PositiveIntegerField()),
                ('power_stock', models.IntegerField(default=0)),
                ('power_date_created', models.DateTimeField(auto_now_add=True)),
                ('power_date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_name', models.CharField(max_length=100)),
                ('processor_brand', models.CharField(max_length=200)),
                ('processor_description', models.TextField(null=True)),
                ('processor_img', models.ImageField(upload_to='store/static/media/products')),
                ('processor_price', models.PositiveIntegerField()),
                ('processor_stock', models.IntegerField(default=0)),
                ('processor_date_created', models.DateTimeField(auto_now_add=True)),
                ('processor_date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('product_price', models.PositiveIntegerField()),
                ('product_img', models.ImageField(upload_to='store/static/media/products')),
                ('product_category', models.CharField(default='General', max_length=200)),
                ('product_brand', models.CharField(default='general', max_length=200)),
                ('product_stock', models.PositiveSmallIntegerField(default=100)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_name', models.CharField(max_length=100)),
                ('ram_brand', models.CharField(max_length=200)),
                ('ram_description', models.TextField(null=True)),
                ('ram_img', models.ImageField(upload_to='store/static/media/products')),
                ('ram_price', models.PositiveIntegerField()),
                ('ram_stock', models.IntegerField(default=0)),
                ('ram_date_created', models.DateTimeField(auto_now_add=True)),
                ('ram_date_modified', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Refrigeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrigeration_name', models.CharField(max_length=100)),
                ('refrigeration_brand', models.CharField(max_length=200)),
                ('refrigeration_description', models.TextField(null=True)),
                ('refrigeration_img', models.ImageField(upload_to='store/static/media/products')),
                ('refrigeration_price', models.PositiveIntegerField()),
                ('refrigeration_stock', models.IntegerField(default=0)),
                ('refrigeration_date_created', models.DateTimeField(auto_now_add=True)),
                ('refrigeration_date_modified', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_name', models.CharField(max_length=100)),
                ('storage_brand', models.CharField(max_length=200)),
                ('storage_description', models.TextField(null=True)),
                ('storage_img', models.ImageField(upload_to='store/static/media/products')),
                ('storage_price', models.PositiveIntegerField()),
                ('storage_stock', models.IntegerField(default=0)),
                ('storage_date_created', models.DateTimeField(auto_now_add=True)),
                ('storage_date_modified', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='processor',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='power_supply',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='headphones',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='graphics_card',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='chair',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='case',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
