# Generated by Django 5.0.6 on 2024-06-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_accessory_case_categorie_chair_graphics_card_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
