# Generated by Django 5.0.6 on 2024-06-19 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_name', models.CharField(max_length=100)),
                ('laptop_brand', models.CharField(max_length=200)),
                ('laptop_description', models.TextField(null=True)),
                ('laptop_img', models.ImageField(upload_to='store/static/media/products')),
                ('laptop_price', models.PositiveIntegerField()),
                ('laptop_stock', models.IntegerField(default=0)),
                ('laptop_date_created', models.DateTimeField(auto_now_add=True)),
                ('laptop_date_modified', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
