# Generated by Django 5.0.6 on 2024-06-20 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='accessory_img',
            field=models.ImageField(upload_to='store/static/media/products/accessories'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_img',
            field=models.ImageField(upload_to='store/static/media/products/cases'),
        ),
        migrations.AlterField(
            model_name='chair',
            name='chair_img',
            field=models.ImageField(upload_to='store/static/media/products/chairs'),
        ),
        migrations.AlterField(
            model_name='graphics_card',
            name='card_img',
            field=models.ImageField(upload_to='store/static/media/products/graphics'),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='headPhones_img',
            field=models.ImageField(upload_to='store/static/media/products/headPhones'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='keyboard_img',
            field=models.ImageField(upload_to='store/static/media/products/keyBoards'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='laptop_img',
            field=models.ImageField(upload_to='store/static/media/products/laptops'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor_img',
            field=models.ImageField(upload_to='store/static/media/products/monitors'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='motherBoard_img',
            field=models.ImageField(upload_to='store/static/media/products/motherBoards'),
        ),
        migrations.AlterField(
            model_name='power_supply',
            name='power_img',
            field=models.ImageField(upload_to='store/static/media/products/powerSuplies'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='processor_img',
            field=models.ImageField(upload_to='store/static/media/products/processors'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ram_img',
            field=models.ImageField(upload_to='store/static/media/products/rams'),
        ),
        migrations.AlterField(
            model_name='refrigeration',
            name='refrigeration_img',
            field=models.ImageField(upload_to='store/static/media/products/refrigerations'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='storage_img',
            field=models.ImageField(upload_to='store/static/media/products/storages'),
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouse_name', models.CharField(max_length=100)),
                ('mouse_brand', models.CharField(max_length=200)),
                ('mouse_description', models.TextField(null=True)),
                ('mouse_img', models.ImageField(upload_to='store/static/media/products/laptops')),
                ('mouse_price', models.PositiveIntegerField()),
                ('mouse_stock', models.IntegerField(default=0)),
                ('mouse_date_created', models.DateTimeField(auto_now_add=True)),
                ('mouse_date_modified', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
