# Generated by Django 5.0.6 on 2024-06-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_accessory_accessory_img_alter_case_case_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='mouse_img',
            field=models.ImageField(upload_to='store/static/media/products/mouses'),
        ),
    ]
