# Generated by Django 5.0.6 on 2024-06-21 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_rename_accessory_brand_accessory_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_stock',
            new_name='stock',
        ),
    ]
